version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./container/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  node-red:
    image: nodered/node-red:2.2.3
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./container/node-red/:/data
